name:                searchengine
version:             0.1.0.0
github:              "checkraiser/searchengine"
license:             BSD3
author:              "Truong Dung"
maintainer:          "checkraiser11@gmail.comm"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/checkraiser/searchengine#readme>

dependencies:
- base >= 4.7 && < 5
- lens-aeson
- bytestring
- text
- containers
- raw-strings-qq
- utf8-string
- taggy-lens
- persistent
- persistent-template
- persistent-postgresql
- monad-logger
- mtl
- aeson
- transformers
- exceptions
- eventstore
- streaming
- streaming-bytestring
- protobuf
- async
- unordered-containers
- safe-exceptions
- hspec
- uuid
- email-validate
- selda
- safe
- servant
- network-uri
- miso
- lens
- servant-client-core
- servant-server
- lucid
- graphql-api
- protolude
library:
  source-dirs: src
default-extensions:
  - NoImplicitPrelude  
  - OverloadedStrings
executables:
  searchengine-api:
    main:                Main.hs
    source-dirs:         api
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - searchengine
    - wai
    - warp
    - servant-client
    - wai-logger
    - servant-lucid
    - lucid
    - clay
    - http-media
    - wai-extra
    - servant-docs
    - miso
    - http-types
  searchengine-web:
    main:                Main.hs
    source-dirs:         web
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - searchengine
    - servant
    - servant-server
    - wai
    - warp
    - servant-client
    - wai-logger
    - servant-lucid
    - lucid
    - clay
    - http-media
    - wai-extra
    - servant-docs
    - miso
tests:
  searchengine-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - searchengine
